services:
  - type: web
    name: rubikproject
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn rubikproject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
