services:
  - type: web
    name: rubik-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: SECRET_KEY
        generateValue: true
      - key: IMGBB_API_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
