# Generated by Django 4.2.28 on 2026-05-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
