# Generated by Django 4.2.28 on 2026-05-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomAdmin',
        ),
    ]
